version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"

# docker exec -it postgres bash
# psql -d postgres -U postgres
# create user tester with password 'tester';
# create database testdb;